### ISSUE TITLE
Support for bidirectional TileLink

### ISSUE THREAD

**Issue by programmerjake** [westerndigitalcorporation/omnixtend#1]
We (libre-riscv.org) are considering adding OmniXtend support to our SoC, however, from what I understand, TileLink doesn't support accessing large amounts of memory without the memory being a slave agent, so we need a path in through the Ethernet port to the memory with the SoC acting as a slave, and we also need the SoC to act as a master to access other memory over the OmniXtend link.

Does OmniXtend support having a single Ethernet link support a bidirectional connection that has both a remote master to local memory/devices TileLink connection, and a local master to remote memory/devices connection? If not I think we should add that capability. Note that having a bidirectional link would not cause a loop in the TileLink agent graph, since each direction would be an independent link connected to different portions of the graph, allowing it to stay a DAG.

Proposed connection graph:
https://salsa.debian.org/Kazan-team/kazan/blob/master/docs/OmniXtend%20Bidirectional.svg

**Comment by wdc-pnl** [comment]
Yes, OmniXtend does support having a single Ethernet link support a bidirectional connection that has both a remote master to local memory/devices TileLink connection, and a local master to remote memory/devices connection.

**Comment by programmerjake** [comment]
Great! Thanks.
